# 
# GitHub Actions workflow.
#
# Automatically publishes the "gateway" microservice on push.
#

name: Publish Gateway

on:
  push:
    branches: 
      - main
    paths:
      - 'gateway/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_PUBLISH_REGISTRY }}
      DOCKER_UN: ${{ secrets.DOCKER_PUBLISH_UN }}
      DOCKER_PW: ${{ secrets.DOCKER_PUBLISH_PW  }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
   
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Build
        run: ./scripts/build-image.sh gateway

      - name: Publish
        run: ./scripts/push-image.sh gateway

      # Installs Node.js (for figit).
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      #
      # Install Kubectl and connect.
      # https://github.com/actions-hub/kubectl
      #
      - uses: actions-hub/kubectl@master
      
      - name: Kubectl test
        run: kubectl get po

      - name: Deploy
        run: npx figit ./scripts/kubernetes/gateway.yaml --output yaml | kubectl apply -f -
