# 
# GitHub Actions workflow.
#
# Automatically publishes the "service" microservice on push.
#

name: Publish Service

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_PUBLISH_REGISTRY }}
      DOCKER_UN: ${{ secrets.DOCKER_PUBLISH_UN }}
      DOCKER_PW: ${{ secrets.DOCKER_PUBLISH_PW  }}
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Build image
        run: ./scripts/build-image.sh service

      - name: Publish image
        run: ./scripts/push-image.sh service
