# 
# GitHub Actions workflow.
#
# Automatically deploys the "worker" microservice on push.
#

name: Deploy Worker

on:
  push:
    branches: 
      - main
    paths:
      - 'worker/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_PUBLISH_REGISTRY }}
      DOCKER_UN: ${{ secrets.DOCKER_PUBLISH_UN }}
      DOCKER_PW: ${{ secrets.DOCKER_PUBLISH_PW  }}
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Build
        run: ./scripts/build-image.sh worker

      - name: Publish
        run: ./scripts/push-image.sh worker

      # Installs Node.js (for figit).
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      #
      # Install Kubectl and connect to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy
        run: npx figit ./scripts/kubernetes/worker.yaml --output yaml | kubectl apply -f -
